import postFormSubmission from '@/common/checklist/postFormSubmission';
import { ApplicationFormType } from '../schema';

const postApplicationForm = async (data: ApplicationFormType, ref: string) => {
    try {
        // const record = {
        //     // system
        //     ref: { value: data.ref },
        //     office: { value: [{ code: data.office }] },
        //     // 1
        //     firstName: { value: data.firstName },
        //     middleName: { value: data.middleName },
        //     lastName: { value: data.lastName },
        //     street: { value: data.street },
        //     city: { value: data.city },
        //     state: { value: data.state },
        //     zip: { value: data.zip },
        //     country: { value: data.country },
        //     phone: { value: data.phone },
        //     email: { value: data.email },
        //     passport: { value: data.passport },
        //     passportExpiration: { value: data.passportExpiration },
        //     passportIssued: { value: data.passportIssued },
        //     age: { value: data.age },
        //     birthDay: { value: data.birthDay },
        //     birthMonth: { value: data.birthMonth },
        //     birthYear: { value: data.birthYear },
        //     ssn: { value: data.ssn },
        //     sex: { value: data.sex },
        //     maritalStatus: { value: data.maritalStatus },
        //     children: { value: data.children },
        //     hasFamilySupport: { value: data.hasFamilySupport },
        //     hasFamilySupportExplain: { value: data.hasFamilySupportExplain },
        //     // 2
        //     healthCondition: { value: data.healthCondition },
        //     seriousInjury: { value: data.seriousInjury },
        //     seriousInjuryExplain: { value: data.seriousInjuryExplain },
        //     hasHandicap: { value: data.hasHandicap },
        //     hasHandicapExplain: { value: data.hasHandicapExplain },
        //     doSmoke: { value: data.doSmoke },
        //     canLift33lbs: { value: data.canLift33lbs },
        //     personalDoctor: { value: data.personalDoctor },
        //     personalDoctorPhone: { value: data.personalDoctorPhone },
        //     // 3
        //     emergencyName: { value: data.emergencyName },
        //     emergencyRelationship: { value: data.emergencyRelationship },
        //     emergencyStreet: { value: data.emergencyStreet },
        //     emergencyCity: { value: data.emergencyCity },
        //     emergencyState: { value: data.emergencyState },
        //     emergencyZip: { value: data.emergencyZip },
        //     emergencyPhone: { value: data.emergencyPhone },
        //     emergencyCountry: { value: data.emergencyCountry },
        //     emergencyEmail: { value: data.emergencyEmail },
        //     // 4
        //     describeMotivation: { value: data.describeMotivation },
        //     areaInterested: { value: data.areaInterested },
        //     otherAreaInterested: { value: data.otherAreaInterested },
        //     minAvailability: { value: data.minAvailability },
        //     maxAvailability: { value: data.maxAvailability },
        //     preferredStartDate: { value: data.preferredStartDate },
        //     preferredStartDate2: { value: data.preferredStartDate2 },
        //     ifNoPosition: { value: data.ifNoPosition },
        //     // 5
        //     educationSchoolName: { value: data.educationSchoolName },
        //     educationDegree: { value: data.educationDegree },
        //     educationDate: { value: data.educationDate },
        //     employProfessional: { value: data.employProfessional },
        //     employAccreditation: { value: data.employAccreditation },
        //     employHistory: { value: data.employHistory },
        //     hobby: { value: data.hobby },
        //     clubs: { value: data.clubs },
        //     serviceOrganizationName: { value: data.serviceOrganizationName },
        //     serviceStartDate: { value: data.serviceStartDate },
        //     serviceEndDate: { value: data.serviceEndDate },
        //     serviceDuties: { value: data.serviceDuties },
        //     hasDriverLicense: { value: data.hasDriverLicense },
        //     hasHeldLicense12Months: { value: data.hasHeldLicense12Months },
        //     drivingViolation: { value: data.drivingViolation },
        //     hasConvictedTrafficAccident: { value: data.hasConvictedTrafficAccident },
        //     hasTrafficAccidentExplain: { value: data.hasTrafficAccidentExplain },
        //     hasVisitedIsrael: { value: data.hasVisitedIsrael },
        //     hasVisitedIsraelDates: { value: data.hasVisitedIsraelDates },
        //     listForeignCountries: { value: data.listForeignCountries },
        //     // 6
        //     churchName: { value: data.churchName },
        //     christianExperience: { value: data.christianExperience },
        //     christianJewishUnderstanding: { value: data.christianJewishUnderstanding },
        //     interestIsrael: { value: data.interestIsrael },
        //     // 7
        //     skillCarpentry: { value: data.skillCarpentry },
        //     skillConstruction: { value: data.skillConstruction },
        //     skillElectrical: { value: data.skillElectrical },
        //     skillForklift: { value: data.skillForklift },
        //     skillMechanic: { value: data.skillMechanic },
        //     skillRepair: { value: data.skillRepair },
        //     skillLaborer: { value: data.skillLaborer },
        //     skillWelding: { value: data.skillWelding },
        //     skillMasonry: { value: data.skillMasonry },
        //     skillPlumbing: { value: data.skillPlumbing },
        //     skillPainting: { value: data.skillPainting },
        //     skillWarehouseMaintenance: { value: data.skillWarehouseMaintenance },
        //     skillTransportation: { value: data.skillTransportation },
        //     hasHeavyLicense: { value: data.hasHeavyLicense },
        //     skillWebsite: { value: data.skillWebsite },
        //     skillWebDesign: { value: data.skillWebDesign },
        //     skillIT: { value: data.skillIT },
        //     skillVideo: { value: data.skillVideo },
        //     skillComputerDesign: { value: data.skillComputerDesign },
        //     skillAdobePhotoshop: { value: data.skillAdobePhotoshop },
        //     skillAdobeInDesign: { value: data.skillAdobeInDesign },
        //     skillOtherPrograms: { value: data.skillOtherPrograms },
        //     skillJournalism: { value: data.skillJournalism },
        //     skillPublicSpeaking: { value: data.skillPublicSpeaking },
        //     skillFilmmaking: { value: data.skillFilmmaking },
        //     skillPhotography: { value: data.skillPhotography },
        //     skillAccounting: { value: data.skillAccounting },
        //     skillAdministration: { value: data.skillAdministration },
        //     skillBookkeeping: { value: data.skillBookkeeping },
        //     skillOperatingSystems: { value: data.skillOperatingSystems },
        //     skillSystem: { value: data.skillSystem },
        //     skillSoftware: { value: data.skillSoftware },
        //     skillOfficeSuite: { value: data.skillOfficeSuite },
        //     skillExcel: { value: data.skillExcel },
        //     skillTyping: { value: data.skillTyping },
        //     skillGoogleDrive: { value: data.skillGoogleDrive },
        //     skillSecretarial: { value: data.skillSecretarial },
        //     skillOrganizing: { value: data.skillOrganizing },
        //     skillLibrary: { value: data.skillLibrary },
        //     skillReception: { value: data.skillReception },
        //     skillProofreading: { value: data.skillProofreading },
        //     skillCopyEditing: { value: data.skillCopyEditing },
        //     skillTranslation: { value: data.skillTranslation },
        //     skillCounseling: { value: data.skillCounseling },
        //     skillMusicalInstrument: { value: data.skillMusicalInstrument },
        //     skillJanitorial: { value: data.skillJanitorial },
        //     skillCooking: { value: data.skillCooking },
        //     skillForeignLanguage: { value: data.skillForeignLanguage },
        //     skillComputer: { value: data.skillComputer },
        //     skillSpecialTraining: { value: data.skillSpecialTraining },
        //     // 8
        //     character1: { value: data.character1 },
        //     character2: { value: data.character2 },
        //     character3: { value: data.character3 },
        //     character4: { value: data.character4 },
        //     // 9
        //     refPastorName: { value: data.refPastorName },
        //     refPastorAddress: { value: data.refPastorAddress },
        //     refPastorPhone: { value: data.refPastorPhone },
        //     refPastorEmail: { value: data.refPastorEmail },
        //     refEmployerName: { value: data.refEmployerName },
        //     refEmployerAddress: { value: data.refEmployerAddress },
        //     refEmployerPhone: { value: data.refEmployerPhone },
        //     refEmployerEmail: { value: data.refEmployerEmail },
        //     refFriendName: { value: data.refFriendName },
        //     refFriendAddress: { value: data.refFriendAddress },
        //     refFriendPhone: { value: data.refFriendPhone },
        //     refFriendEmail: { value: data.refFriendEmail },
        //     refOtherName: { value: data.refOtherName },
        //     refOtherAddress: { value: data.refOtherAddress },
        //     refOtherPhone: { value: data.refOtherPhone },
        //     refOtherEmail: { value: data.refOtherEmail },
        //     refOtherRelationship: { value: data.refOtherRelationship },
        //     hasFriendsIsrael: { value: data.hasFriendsIsrael },
        //     hasFriendsIsraelExplain: { value: data.hasFriendsIsraelExplain },
        //     // 10
        //     verify: { value: data.verify }
        // };
        // const res = await fetch('/api/reference/postPersonalHealthQuestionnaire', {
        //     method: 'POST',
        //     headers: {
        //         'Content-Type': 'application/json'
        //     },
        //     body: JSON.stringify(record) // Replace with your data
        // });
        // const res2 = await postFormSubmission(ref);
        // console.log(res);
        // if (res.ok) {
        //     return res;
        // } else {
        //     alert('Something wrong. Could not save your answers.');
        //     return;
        // }
    } catch (error) {
        console.error('Error posting personal health questionnaire:', error);
        alert('An error occurred while submitting your answers.');
    }
};
export default postApplicationForm;

const data = {
    areaInterested: ['Publications/Media'],
    educationTable: [
        {
            educationSchoolName: 'asf',
            educationDegree: 'daf',
            educationDate: '01/01/2000'
        },
        {
            educationSchoolName: 'adf',
            educationDegree: 'asdf',
            educationDate: '01/01/2000'
        },
        {
            educationSchoolName: '',
            educationDegree: '',
            educationDate: ''
        },
        {
            educationSchoolName: '',
            educationDegree: '',
            educationDate: ''
        },
        {
            educationSchoolName: '',
            educationDegree: '',
            educationDate: ''
        }
    ],
    character1: ['Firm', 'Take charge', 'Determined'],
    character2: ['Visionary', 'Take risks', 'Energetic'],
    character3: ['Loyal', 'Even-keeled', 'Non-demanding'],
    character4: [],
    skillCarpentry: '4',
    skillConstruction: '3',
    skillElectrical: '1',
    skillForklift: '0',
    skillMechanic: '0',
    skillRepair: '0',
    skillLaborer: '0',
    skillWelding: '0',
    skillMasonry: '0',
    skillPlumbing: '0',
    skillPainting: '0',
    skillWarehouseMaintenance: '0',
    skillTransportation: '0',
    skillWebsite: '0',
    skillWebDesign: '0',
    skillIT: '0',
    skillVideo: '0',
    skillComputerDesign: '0',
    skillAdobePhotoshop: '0',
    skillAdobeInDesign: '0',
    skillOtherPrograms: '0',
    skillJournalism: '0',
    skillPublicSpeaking: '0',
    skillFilmmaking: '0',
    skillPhotography: '0',
    skillAccounting: '0',
    skillAdministration: '0',
    skillBookkeeping: '0',
    skillOperatingSystems: '0',
    skillSystem: '0',
    skillSoftware: '0',
    skillOfficeSuite: '0',
    skillExcel: '0',
    skillTyping: '0',
    skillGoogleDrive: '0',
    skillSecretarial: '0',
    skillOrganizing: '0',
    skillLibrary: '0',
    skillReception: '0',
    skillProofreading: '0',
    skillCopyEditing: '0',
    skillTranslation: '0',
    skillCounseling: '0',
    skillMusicalInstrument: '0',
    skillJanitorial: '0',
    skillCooking: '0',
    firstName: 'a',
    middleName: 'asfd',
    lastName: 'a',
    street: 'a',
    city: 'aasf',
    zip: 'aasfd',
    state: 'asa',
    country: 'aasf',
    phone: 'a',
    email: 'a@a.aa',
    passportNumber: 'a',
    passportExpiration: '01/01/2000',
    passportIssued: 'a',
    birthday: '01/01/2000',
    age: '12',
    ssn: '',
    sex: 'Female',
    maritalStatus: 'Single',
    hasChildren: 'No',
    hasFamilySupport: 'No',
    hasFamilySupportExplain: 'a',
    ref: '58',
    office: 'Japan',
    verify1: true,
    verify2: true,
    verify3: true,
    verify4: true,
    verify5: true,
    verify6: true,
    verify7: true,
    healthCondition: 'Excellent',
    seriousInjury: 'No',
    seriousInjuryExplain: 'ad',
    hasHandicap: 'Yes',
    hasHandicapExplain: 'af',
    doSmoke: 'Yes',
    canLift33lbs: 'No',
    personalDoctor: 'asf',
    personalDoctorPhone: 'asfd',
    emergencyName: 'as',
    emergencyRelationship: 'fdasdf',
    emergencyEmail: 'a@a.aa',
    emergencyPhone: 'asfd',
    emergencyStreet: 'asfd',
    emergencyState: 'as',
    emergencyCity: 'fsad',
    emergencyCountry: 'asfd',
    emergencyZip: 'fsadf',
    describeMotivation: 'asdf',
    otherAreaInterested: 'asf',
    minAvailability: 'sdaf',
    maxAvailability: 'sa',
    preferredStartDate: '01/01/2000',
    preferredStartDate2: '01/01/2000',
    ifNoPosition: 'No',
    employTable: [
        {
            employDate: 'sda',
            employName: 'fadf',
            employAddress: 'sadf',
            employDuties: 'sadf',
            employLeavingReason: 'asdfa'
        },
        {
            employDate: 'sad',
            employName: 'sdf',
            employAddress: 'df',
            employDuties: 'f',
            employLeavingReason: 'sfd'
        },
        {
            employDate: '',
            employName: '',
            employAddress: '',
            employDuties: '',
            employLeavingReason: ''
        },
        {
            employDate: '',
            employName: '',
            employAddress: '',
            employDuties: '',
            employLeavingReason: ''
        },
        {
            employDate: '',
            employName: '',
            employAddress: '',
            employDuties: '',
            employLeavingReason: ''
        }
    ],
    hobby: 'asfd',
    clubs: 'asfd',
    serviceTable: [
        {
            serviceOrganizationName: 'asfd',
            serviceStartDate: '01/01/2000',
            serviceEndDate: '01/01/2000',
            serviceDuties: 'sadf'
        },
        {
            serviceOrganizationName: 'safd',
            serviceStartDate: '01/01/2000',
            serviceEndDate: '01/01/2000',
            serviceDuties: 'asfd'
        },
        {
            serviceOrganizationName: '',
            serviceStartDate: '',
            serviceEndDate: '',
            serviceDuties: ''
        },
        {
            serviceOrganizationName: '',
            serviceStartDate: '',
            serviceEndDate: '',
            serviceDuties: ''
        },
        {
            serviceOrganizationName: '',
            serviceStartDate: '',
            serviceEndDate: '',
            serviceDuties: ''
        }
    ],
    hasDriverLicense: 'No',
    hasLicenseMoreThanTwelveMonths: 'No',
    drivingViolation: 'asdf',
    hasConvictedTrafficAccident: 'Yes',
    hasTrafficAccidentExplain: 'asfd',
    hasVisitedIsrael: 'Yes',
    hasVisitedIsraelDates: 'fdas',
    listForeignCountries: 'asfd',
    churchName: 'asf',
    christianExperience: 'asfd',
    christianJewishUnderstanding: 'asfd',
    interestIsrael: 'asf',
    hasHeavyLicense: 'No',
    skillForeignLanguage: 'asdf',
    skillComputer: 'safd',
    skillSpecialTraining: 'asdf',
    refPastorName: 'a',
    refPastorPhone: 'fasdf',
    refPastorEmail: 'a@a.aa',
    refPastorAddress: 'asdfa',
    refEmployerName: 'afadsf',
    refEmployerPhone: 'asdf',
    refEmployerEmail: 'a@a.aa',
    refEmployerAddress: 'asfd',
    refFriendName: 'asf',
    refFriendPhone: 'asf',
    refFriendEmail: 'a@a.aa',
    refFriendAddress: 'asf',
    refOtherName: 'asf',
    refOtherPhone: 'asfd',
    refOtherEmail: 'asdf',
    refOtherAddress: 'asf',
    refOtherRelationship: 'asfd',
    hasFriendsIsrael: 'No',
    hasFriendsIsraelExplain: 'asfd'
};
