export type formtype =
    | "firstName"
    | "lastName"
    | "IDType"
    | "IDNumber"
    | "gender"
    | "birthday"
    | "originCity"
    | "originCountry"
    | "nativeLanguage"
    | "birthmonth"
    | "birthyear"
    | "phone"
    | "email"
    | "address1"
    | "address2"
    | "city"
    | "zip"
    // | "maritalStatus"
    // | "spouseFirstName"
    // | "spouseFamilyName"
    // | "spouseIDType"
    // | "spouseIDNumber"
    // | "spouseBirthday"
    // | "childStatus"
    // | "childFirstName"
    // | "childLastName"
    // | "childGender"
    // | "childAccompanied"
    // | "childBirthday"
    // | "itemRows";