export interface PersonalHealthQuestionnaire {
    epilepsy: kintone.fieldTypes.DropDown;
    abnormalBleeding: kintone.fieldTypes.DropDown;
    heartProblems: kintone.fieldTypes.DropDown;
    shortBreath: kintone.fieldTypes.DropDown;
    lossVision: kintone.fieldTypes.DropDown;
    fatigue: kintone.fieldTypes.DropDown;
    ref: kintone.fieldTypes.Number;
    hiv: kintone.fieldTypes.DropDown;
    heightUnit: kintone.fieldTypes.RadioButton;
    height: kintone.fieldTypes.Number;
    headInjury: kintone.fieldTypes.DropDown;
    vomiting: kintone.fieldTypes.DropDown;
    Text_1: kintone.fieldTypes.SingleLineText;
    dizziness: kintone.fieldTypes.DropDown;
    migranes: kintone.fieldTypes.DropDown;
    tuberculosis: kintone.fieldTypes.DropDown;
    weight: kintone.fieldTypes.Number;
    asthma: kintone.fieldTypes.DropDown;
    backProblems: kintone.fieldTypes.DropDown;
    highBloodPressure: kintone.fieldTypes.DropDown;
    anemia: kintone.fieldTypes.DropDown;
    anxiety: kintone.fieldTypes.DropDown;
    brokenBones: kintone.fieldTypes.DropDown;
    arthritis: kintone.fieldTypes.DropDown;
    name: kintone.fieldTypes.SingleLineText;
    weightUnit: kintone.fieldTypes.RadioButton;
    neckPain: kintone.fieldTypes.DropDown;
    lossHearing: kintone.fieldTypes.DropDown;
    emphysema: kintone.fieldTypes.DropDown;
    weakness: kintone.fieldTypes.DropDown;
    q1: kintone.fieldTypes.MultiLineText;
    q2: kintone.fieldTypes.MultiLineText;
    q3: kintone.fieldTypes.MultiLineText;
    q4: kintone.fieldTypes.MultiLineText;
    q5: kintone.fieldTypes.MultiLineText;
    q6: kintone.fieldTypes.MultiLineText;
    fainting: kintone.fieldTypes.DropDown;
    hepatitis: kintone.fieldTypes.DropDown;
    stroke: kintone.fieldTypes.DropDown;
    hemorrhoids: kintone.fieldTypes.DropDown;
    cancer: kintone.fieldTypes.DropDown;
    depression: kintone.fieldTypes.DropDown;
    diabetes: kintone.fieldTypes.DropDown;
    age: kintone.fieldTypes.Number;

    office: kintone.fieldTypes.UserSelect;
}
export interface SavedPersonalHealthQuestionnaire extends PersonalHealthQuestionnaire {
    $id: kintone.fieldTypes.Id;
    $revision: kintone.fieldTypes.Revision;
    Updated_by: kintone.fieldTypes.Modifier;
    Created_by: kintone.fieldTypes.Creator;
    Created_datetime: kintone.fieldTypes.CreatedTime;
    Record_number: kintone.fieldTypes.RecordNumber;
    Updated_datetime: kintone.fieldTypes.UpdatedTime;
}
import { KintoneRecordField } from '@kintone/rest-api-client';

export type REST_PersonalHealthQuestionnaire = {
    epilepsy: KintoneRecordField.DropDown;
    abnormalBleeding: KintoneRecordField.DropDown;
    heartProblems: KintoneRecordField.DropDown;
    shortBreath: KintoneRecordField.DropDown;
    lossVision: KintoneRecordField.DropDown;
    fatigue: KintoneRecordField.DropDown;
    ref: KintoneRecordField.Number;
    hiv: KintoneRecordField.DropDown;
    heightUnit: KintoneRecordField.RadioButton;
    height: KintoneRecordField.Number;
    headInjury: KintoneRecordField.DropDown;
    vomiting: KintoneRecordField.DropDown;
    Text_1: KintoneRecordField.SingleLineText;
    dizziness: KintoneRecordField.DropDown;
    migranes: KintoneRecordField.DropDown;
    tuberculosis: KintoneRecordField.DropDown;
    weight: KintoneRecordField.Number;
    asthma: KintoneRecordField.DropDown;
    backProblems: KintoneRecordField.DropDown;
    highBloodPressure: KintoneRecordField.DropDown;
    anemia: KintoneRecordField.DropDown;
    anxiety: KintoneRecordField.DropDown;
    brokenBones: KintoneRecordField.DropDown;
    arthritis: KintoneRecordField.DropDown;
    name: KintoneRecordField.SingleLineText;
    weightUnit: KintoneRecordField.RadioButton;
    neckPain: KintoneRecordField.DropDown;
    lossHearing: KintoneRecordField.DropDown;
    emphysema: KintoneRecordField.DropDown;
    weakness: KintoneRecordField.DropDown;
    q1: KintoneRecordField.MultiLineText;
    q2: KintoneRecordField.MultiLineText;
    q3: KintoneRecordField.MultiLineText;
    q4: KintoneRecordField.MultiLineText;
    q5: KintoneRecordField.MultiLineText;
    q6: KintoneRecordField.MultiLineText;
    fainting: KintoneRecordField.DropDown;
    hepatitis: KintoneRecordField.DropDown;
    stroke: KintoneRecordField.DropDown;
    hemorrhoids: KintoneRecordField.DropDown;
    cancer: KintoneRecordField.DropDown;
    depression: KintoneRecordField.DropDown;
    diabetes: KintoneRecordField.DropDown;
    age: KintoneRecordField.Number;

    office: KintoneRecordField.UserSelect;
};
export type REST_SavedPersonalHealthQuestionnaire = REST_PersonalHealthQuestionnaire & {
    $id: KintoneRecordField.Id;
    $revision: KintoneRecordField.Revision;
    Updated_by: KintoneRecordField.Modifier;
    Created_by: KintoneRecordField.Creator;
    Created_datetime: KintoneRecordField.CreatedTime;
    Record_number: KintoneRecordField.RecordNumber;
    Updated_datetime: KintoneRecordField.UpdatedTime;
};
